### ISSUE TITLE
Linter for checks on markdown metadata

### ISSUE THREAD

**Issue by arthurlutz** [plainionist/Plainion.JekyllLint#2]
It would be awesome if Plainion.JekyllLint could have a way for user configured checks on markdown metadata for articles. In my use case there are a bunch of taxonomies used and I would like to check they are correctly written (for example listing taxonomies used, or even listing possible values for a given taxonomy). This could avoid getting a new category because of a typo

**Comment by plainionist** [comment]
Could you pls post a code snippet of such a meta data and an concrete example of a "finding"?

**Comment by plainionist** [comment]
No update since years

**Comment by plainionist** [comment]
No update since years

**Comment by plainionist** [comment]
No update since years
